---
- name: firefox | Collect dependencies for system Firefox
  shell: 'apt-get install -s firefox | grep Inst | grep -v firefox | cut -d" " -f 2'
  register: firefox_apt_deps
  when: (ansible_pkg_mgr == "apt")

- name: firefox | Install dependencies
  apt: name="{{item}}" state="latest" update_cache="yes"
  with_items: firefox_apt_deps.stdout_lines
  when: firefox_apt_deps.stdout_lines is defined

- name: firefox | Create install dir
  file:
    path: "{{firefox_install_root}}/firefox-{{firefox_version}}"
    state: directory

- name: firefox | Extract archive
  unarchive:
    remote_src: yes
    src: "{{firefox_temp_dir.path}}/{{firefox_archive_name}}"
    dest: "{{firefox_install_root}}/firefox-{{firefox_version}}"
    extra_opts: [ '--strip-components=1' ]
    creates: "{{firefox_install_root}}/firefox-{{firefox_version}}/firefox"

- name: firefox | Link to current version
  file: src='{{firefox_install_root}}/firefox-{{firefox_version}}/firefox' dest='{{firefox_link_dir}}/firefox' force=yes state='link'
