---
- name: firefox | Check if Firefox is present
  stat:
    path: "{{firefox_install_root}}/firefox-{{firefox_version}}/firefox"
  register: firefox_stat

- name: firefox | Set install fact
  set_fact: firefox_needs_install=True
  when: not firefox_stat.stat.exists
